.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. xuez_qt
clean: FORCE
	$(MAKE) -C .. xuez_qt_clean
check: FORCE
	$(MAKE) -C .. test_xuez_qt_check
xuez-qt xuez-qt.exe: FORCE
	 $(MAKE) -C .. xuez_qt
apk: FORCE
	$(MAKE) -C .. xuez_qt_apk
